# Generated by Django 6.0 on 2025-12-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'icône (ex: heart, book, globe)",
                        max_length=50,
                        verbose_name="Icône",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#C75B2A",
                        help_text="Code couleur hexadécimal",
                        max_length=20,
                        verbose_name="Couleur",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Catégorie de projet",
                "verbose_name_plural": "Catégories de projets",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Affichée dans les listes et cartes",
                        max_length=300,
                        verbose_name="Description courte",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description complète")),
                (
                    "impact_description",
                    models.TextField(
                        blank=True,
                        help_text="Décrivez l'impact de ce projet",
                        verbose_name="Impact attendu",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        upload_to="projects/featured/", verbose_name="Image principale"
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des URLs d'images",
                        verbose_name="Galerie d'images",
                    ),
                ),
                ("video_url", models.URLField(blank=True, verbose_name="URL vidéo")),
                (
                    "location",
                    models.CharField(
                        default="Dschang, Cameroun", max_length=200, verbose_name="Lieu"
                    ),
                ),
                (
                    "location_coordinates",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Coordonnées GPS"
                    ),
                ),
                (
                    "goal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Objectif financier",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant actuel",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("active", "Actif"),
                            ("funded", "Financé"),
                            ("completed", "Terminé"),
                            ("paused", "En pause"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "is_urgent",
                    models.BooleanField(default=False, verbose_name="Urgent"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin prévue"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="projects.projectcategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-is_featured", "-is_urgent", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "need_type",
                    models.CharField(
                        choices=[("financial", "Financier"), ("material", "Matériel")],
                        max_length=20,
                        verbose_name="Type de besoin",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Montant cible",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Montant actuel",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nom de l'article"
                    ),
                ),
                (
                    "quantity_needed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité nécessaire"
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité reçue"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Ex: pièces, kg, boîtes",
                        max_length=50,
                        verbose_name="Unité",
                    ),
                ),
                (
                    "is_fulfilled",
                    models.BooleanField(default=False, verbose_name="Accompli"),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 = haute priorité",
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Besoin du projet",
                "verbose_name_plural": "Besoins des projets",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="projects/updates/", verbose_name="Image"
                    ),
                ),
                (
                    "is_milestone",
                    models.BooleanField(
                        default=False,
                        help_text="Marquer comme étape importante",
                        verbose_name="Jalon important",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mise à jour du projet",
                "verbose_name_plural": "Mises à jour des projets",
                "ordering": ["-created_at"],
            },
        ),
    ]
