# Generated by Django 6.0 on 2025-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="featured_image_url",
            field=models.URLField(
                blank=True,
                help_text="Utilisez une URL si pas d'image uploadée",
                verbose_name="URL image externe",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                upload_to="projects/featured/",
                verbose_name="Image principale",
            ),
        ),
    ]
