# Generated by Django 6.0 on 2025-12-26 13:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(max_length=200, verbose_name="Nom du donateur"),
                ),
                (
                    "donor_email",
                    models.EmailField(max_length=254, verbose_name="Email du donateur"),
                ),
                (
                    "donor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Ne pas afficher le nom publiquement",
                        verbose_name="Don anonyme",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro (€)"),
                            ("USD", "US Dollar ($)"),
                            ("XAF", "CFA Franc (FCFA)"),
                            ("GBP", "British Pound (£)"),
                        ],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("fapshi", "Fapshi"),
                            ("bank", "Virement bancaire"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Méthode de paiement",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe Session ID"
                    ),
                ),
                (
                    "fapshi_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fapshi Transaction ID"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Message optionnel du donateur",
                        verbose_name="Message du donateur",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Complété le"
                    ),
                ),
                (
                    "receipt_sent",
                    models.BooleanField(default=False, verbose_name="Reçu envoyé"),
                ),
                (
                    "thank_you_sent",
                    models.BooleanField(
                        default=False, verbose_name="Remerciement envoyé"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Laissez vide pour un don général",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "project_need",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="projects.projectneed",
                        verbose_name="Besoin spécifique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Don",
                "verbose_name_plural": "Dons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de l'impact"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icône"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "project_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.projectcategory",
                        verbose_name="Catégorie de projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impact de don",
                "verbose_name_plural": "Impacts de dons",
                "ordering": ["order", "amount"],
            },
        ),
        migrations.CreateModel(
            name="MaterialContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "contributor_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom du contributeur"
                    ),
                ),
                (
                    "contributor_email",
                    models.EmailField(max_length=254, verbose_name="Email"),
                ),
                (
                    "contributor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de la contribution"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valeur estimée",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pledged", "Promis"),
                            ("confirmed", "Confirmé"),
                            ("delivered", "Livré"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pledged",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de livraison prévue"
                    ),
                ),
                (
                    "delivery_notes",
                    models.TextField(blank=True, verbose_name="Notes de livraison"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "project_need",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_contributions",
                        to="projects.projectneed",
                        verbose_name="Besoin du projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contribution matérielle",
                "verbose_name_plural": "Contributions matérielles",
                "ordering": ["-created_at"],
            },
        ),
    ]
