# Generated by Django 5.2.8 on 2025-12-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationimpact",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Photo illustrant l'impact (ex: bénéficiaire)",
                null=True,
                upload_to="donations/impact/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="donationimpact",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Afficher en priorité sur la page de dons",
                verbose_name="Mis en avant",
            ),
        ),
        migrations.AddField(
            model_name="donationimpact",
            name="short_story",
            field=models.CharField(
                blank=True,
                help_text="Ex: Marie a reçu ses fournitures scolaires grâce aux donateurs",
                max_length=200,
                verbose_name="Courte histoire",
            ),
        ),
    ]
