# Generated by Django 6.0 on 2025-12-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_replied",
                    models.BooleanField(default=False, verbose_name="Répondu"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Réponse")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Dons, Projets, Général",
                        max_length=100,
                        verbose_name="Catégorie",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ImpactStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Titre")),
                (
                    "value",
                    models.CharField(
                        help_text="Ex: 500+, 10000, 25",
                        max_length=50,
                        verbose_name="Valeur",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Ex: familles, élèves, projets",
                        max_length=50,
                        verbose_name="Suffixe",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="Icône"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Statistique d'impact",
                "verbose_name_plural": "Statistiques d'impact",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "subscribed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inscrit le"),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Désinscrit le"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="fr", max_length=2, verbose_name="Langue préférée"
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonné newsletter",
                "verbose_name_plural": "Abonnés newsletter",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sponsor", "Sponsor"),
                            ("partner", "Partenaire"),
                            ("supporter", "Soutien"),
                            ("media", "Média"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("logo", models.ImageField(upload_to="partners/", verbose_name="Logo")),
                ("website", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="FDTM", max_length=100, verbose_name="Nom du site"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Construire un avenir plus lumineux, main dans la main",
                        max_length=200,
                        verbose_name="Slogan",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(blank=True, verbose_name="Texte À propos"),
                ),
                (
                    "mission_text",
                    models.TextField(blank=True, verbose_name="Texte Mission"),
                ),
                (
                    "vision_text",
                    models.TextField(blank=True, verbose_name="Texte Vision"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="contact@fdtm.org",
                        max_length=254,
                        verbose_name="Email de contact",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ex: {"facebook": "url", "instagram": "url"}',
                        verbose_name="Liens sociaux",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(blank=True, verbose_name="Texte du pied de page"),
                ),
                (
                    "default_meta_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        verbose_name="Meta description par défaut",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID Google Analytics"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres du site",
                "verbose_name_plural": "Paramètres du site",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("founder", "Fondateur"),
                            ("board", "Conseil d'administration"),
                            ("staff", "Personnel"),
                            ("volunteer", "Bénévole"),
                            ("partner", "Partenaire"),
                        ],
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Titre/Fonction"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biographie")),
                ("photo", models.ImageField(upload_to="team/", verbose_name="Photo")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "show_on_homepage",
                    models.BooleanField(
                        default=False, verbose_name="Afficher sur l'accueil"
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("beneficiary", "Bénéficiaire"),
                            ("donor", "Donateur"),
                            ("partner", "Partenaire"),
                            ("volunteer", "Bénévole"),
                        ],
                        default="beneficiary",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu"),
                ),
                ("quote", models.TextField(verbose_name="Témoignage")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="testimonials/", verbose_name="Photo"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="testimonials",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
