# Generated by Django 6.0 on 2025-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="photo_url",
            field=models.URLField(blank=True, verbose_name="URL photo"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="team/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(
                choices=[
                    ("founder", "Fondateur"),
                    ("board", "Conseil d'administration"),
                    ("staff", "Personnel"),
                    ("volunteer", "Bénévole"),
                    ("partner", "Partenaire"),
                ],
                default="staff",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
