# Generated by Django 6.0 on 2025-12-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_event"),
        ("projects", "0002_project_featured_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Titre"),
                ),
                ("caption", models.TextField(blank=True, verbose_name="Légende")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="gallery/", verbose_name="Image"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Utilisez ceci pour les images externes",
                        verbose_name="URL de l'image",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                (
                    "date_taken",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de prise"
                    ),
                ),
                (
                    "photographer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Photographe"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mise en avant"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_gallery_images",
                        to="projects.project",
                        verbose_name="Projet associé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image de galerie",
                "verbose_name_plural": "Images de galerie",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
