# Generated by Django 5.2.8 on 2025-12-27 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_gallery_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Numéro de chapitre"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Sous-titre"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Texte principal du chapitre",
                        verbose_name="Contenu",
                    ),
                ),
                (
                    "chapter_type",
                    models.CharField(
                        choices=[
                            ("story", "Histoire / Récit"),
                            ("impact", "Chiffres d'impact"),
                            ("testimonial", "Témoignage"),
                            ("timeline", "Chronologie"),
                            ("highlight", "Mise en avant"),
                        ],
                        default="story",
                        max_length=20,
                        verbose_name="Type de chapitre",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#0066FF",
                        help_text="Couleur hexadécimale, ex: #0066FF",
                        max_length=7,
                        verbose_name="Couleur d'accent",
                    ),
                ),
                (
                    "dark_background",
                    models.BooleanField(default=False, verbose_name="Fond sombre"),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        upload_to="chapters/",
                        verbose_name="Image de fond (upload)",
                    ),
                ),
                (
                    "background_image_url",
                    models.URLField(blank=True, verbose_name="Image de fond (URL)"),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Texte du bouton"
                    ),
                ),
                (
                    "cta_url",
                    models.CharField(
                        blank=True,
                        help_text="URL ou nom de vue Django, ex: core:about",
                        max_length=200,
                        verbose_name="Lien du bouton",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex: [{"value": "520+", "label": "Familles aidées"}]',
                        verbose_name="Statistiques",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Publié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "gallery_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chapter_backgrounds",
                        to="core.galleryimage",
                        verbose_name="Image de galerie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chapitre d'accueil",
                "verbose_name_plural": "Chapitres d'accueil",
                "ordering": ["order", "chapter_number"],
            },
        ),
    ]
