# Generated by Django 6.0 on 2025-12-26 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Catégorie d'article",
                "verbose_name_plural": "Catégories d'articles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=280, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Résumé affiché dans les listes",
                        max_length=400,
                        verbose_name="Extrait",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "featured_image",
                    models.ImageField(
                        upload_to="articles/featured/", verbose_name="Image principale"
                    ),
                ),
                (
                    "image_caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende de l'image"
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez si cet article concerne tous les projets",
                        verbose_name="Article global",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nom de l'auteur"
                    ),
                ),
                (
                    "author_bio",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Bio de l'auteur"
                    ),
                ),
                (
                    "author_photo",
                    models.ImageField(
                        blank=True,
                        upload_to="articles/authors/",
                        verbose_name="Photo de l'auteur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Mis en avant"),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Titre SEO"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Description SEO"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Laissez vide pour un article global",
                        related_name="articles",
                        to="projects.project",
                        verbose_name="Projets associés",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="articles.articlecategory",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-is_featured", "-published_date"],
            },
        ),
        migrations.CreateModel(
            name="ArticleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="articles/gallery/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Légende"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="articles.article",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image d'article",
                "verbose_name_plural": "Images d'articles",
                "ordering": ["order"],
            },
        ),
    ]
