# Generated by Django 6.0 on 2025-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured_image_url",
            field=models.URLField(
                blank=True,
                help_text="Utilisez une URL si pas d'image uploadée",
                verbose_name="URL image externe",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reading_time",
            field=models.PositiveIntegerField(
                default=3, verbose_name="Temps de lecture (min)"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                upload_to="articles/featured/",
                verbose_name="Image principale",
            ),
        ),
    ]
